,

  {
    "id" : 2,
    "appName" : "Ganassi Timeline",
    "company" : "Ganassi Racing",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "false",
    "dataIpad" : "true",
    "dataIphone" : "false",
    "dataKiosk" : "true",
    "dataBrandColor" : "#212123",
    "dataBrandColor2" : "#353535", //title background
    "dataBrandColor3" : "#dc1c27", //app title color
    "dataBrandColor4" : "#202020", //arrow title color
    "dataBrandColorGradient" : "#322e2f",

    "titleBG" : "#353535",
    "appTitle" : "#1d1d1d",
    "companyTitle" : "#DDDDDD",
    "titleArrow" : "#dc1c27",
    "dataIcon" : "icon-ganassi.jpg"
  },

  {
    "id" : 3,
    "appName" : "Multitaction Table",
    "company" : "Fisher Island",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "false",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "true",
    "dataBrandColor" : "#de1b23",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#f01720",

    "titleBG" : "#04626a",
    "appTitle" : "#feffff",
    "loadBrandColor" : "#c05b15",
    "companyTitle" : "#c05b15",
    "titleArrow" : "#c05b15",
    "dataIcon" : "icon-fisher.png",
    "brandGradientTop" : "#04626a",
    "brandGradientBottom" : "#14938a",
    "brandGradientTop2" : "#eae2e0",
    "brandGradientBottom2" : "#cdb19b",
    "brandGradientTileTop" : "#eae2e0",
    "brandGradientTileBottom" : "#cdb19b",
    "snippetTitleColor" : "#04626a",
    "snippetTextColor" : "#252525",
    "imageTile1" : "fisher-1.jpg",
    "imageTile1Y" : "0px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "World Class Amenities",
    "imageTile2" : "fisher-2.jpg",
    "imageTile2Y" : "0px",
    "imageTile2S" : "100%%",
    "snippetTile2Title" : "Unit Fiducial",
    "imageTile3" : "fisher-3.jpg",
    "imageTile3Y" : "0px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Palazzo Del Sol",
    "imageTile4" : "fisher-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "100%",
    "snippetTile4Title" : "Fisher Island Home Screen",
    "imageTile5" : "fisher-5.jpg",
    "imageTile5Y" : "0px",
    "imageTile5S" : "100%",
    "snippetTile5Title" : "Designer Fiducial",
    "imageTile6" : "fisher-6.jpg",
    "imageTile6Y" : "0px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Explore the Fisher Island",

    "powerpointColor1" : "#de1b23",
    "powerpointColor2" : "#14938a",
    "powerpointImage1" : "fisher-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Learn about the amenities!",
    "powerpointImage2" : "fisher-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Explore the Palazzo",
    "powerpointImage3" : "fisher-4.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Multitaction Table Interaction"
  },

  {
    "id" : 4,
    "appName" : "FiOS",
    "company" : "Verizon",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "true",
    "dataIphone" : "true",
    "dataKiosk" : "true",
    "dataBrandColor" : "#de1b23",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#f01720",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#de1b23",
    "companyTitle" : "#de1b23",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-fios.jpg",
    "brandGradientTop" : "#f01720",
    "brandGradientBottom" : "#de1b23",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "fios-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "150%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "fios-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "128%%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "fios-3.jpg",
    "imageTile3Y" : "0px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "fios-4.jpg",
    "imageTile4Y" : "-45px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "fios-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "fios-6.jpg",
    "imageTile6Y" : "0px",
    "imageTile6S" : "128%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#de1b23",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "fios-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "fios-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "fios-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 5,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 6,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 7,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 8,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 9,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  },

  {
    "id" : 10,
    "appName" : "Target Gift Registry",
    "company" : "Target",
    "description" : "This is a brief description of an app.  It'll cover basic functionality, maketing impact, awards won, among any other relevent information about the app.",
    "dataAndroid" : "true",
    "dataIpad" : "false",
    "dataIphone" : "false",
    "dataKiosk" : "false",
    "dataBrandColor" : "#CC0000",
    "dataBrandColor2" : "#ffffff",
    "dataBrandColor3" : "#7F7F7F",
    "dataBrandColor4" : "#000000",
    "dataBrandColorGradient" : "#de2c2c",

    "titleBG" : "#ffffff",
    "appTitle" : "#7F7F7F",
    "loadBrandColor" : "#CC0000",
    "companyTitle" : "#CC0000",
    "titleArrow" : "#000000",
    "dataIcon" : "icon-target.jpg",
    "brandGradientTop" : "#de2c2c",
    "brandGradientBottom" : "#CC0000",
    "brandGradientTop2" : "#a2a2a2",
    "brandGradientBottom2" : "#7F7F7F",
    "snippetTitleColor" : "#d4d4d4",
    "snippetTextColor" : "#252525",
    "imageTile1" : "target-1.jpg",
    "imageTile1Y" : "-55px",
    "imageTile1S" : "100%",
    "snippetTile1Title" : "Gift Registry Home Screen",
    "imageTile2" : "target-2.jpg",
    "imageTile2Y" : "-10px",
    "imageTile2S" : "100%",
    "snippetTile2Title" : "Scanner Animations",
    "imageTile3" : "target-3.jpg",
    "imageTile3Y" : "-150px",
    "imageTile3S" : "100%",
    "snippetTile3Title" : "Registry Creation",
    "imageTile4" : "target-4.jpg",
    "imageTile4Y" : "0px",
    "imageTile4S" : "150%",
    "snippetTile4Title" : "Kiosk Recommendation Mode",
    "imageTile5" : "target-5.jpg",
    "imageTile5Y" : "-30px",
    "imageTile5S" : "150%",
    "snippetTile5Title" : "Product Detail View",
    "imageTile6" : "target-6.jpg",
    "imageTile6Y" : "-200px",
    "imageTile6S" : "100%",
    "snippetTile6Title" : "Customized Registries",

    "powerpointColor1" : "#CC0000",
    "powerpointColor2" : "#7F7F7F",
    "powerpointImage1" : "target-1.jpg",
    "powerpointImage1Y" : "0px",
    "powerpointImage1S" : "100%",
    "powerpointTitle1" : "Welcome To Your Registry!",
    "powerpointImage2" : "target-3.jpg",
    "powerpointImage2Y" : "0px",
    "powerpointImage2S" : "100%",
    "powerpointTitle2" : "Intuitive Design",
    "powerpointImage3" : "target-2.jpg",
    "powerpointImage3Y" : "0px",
    "powerpointImage3S" : "100%",
    "powerpointTitle3" : "Scan Registry Recommendations"
  }